# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40b0a2ffe54f755b4b53e1cdfc424e43467a147813312b73807f7241077855a9c9ef700aedf6ad05b8e098aac9ab2197287fbd97610a2eaaded864aa00e82dd
  petfinder_key: <%= ENV['PETFINDER_KEY'] %>
  petfinder_secret: <%= ENV['PETFINDER_SECRET'] %>
  rescue_group_key: <%= ENV['RESCUEGROUP_KEY'] %>

test:
  secret_key_base: 8a8baf4ac06185a2debd0ccf2e4ffcd3e09eba37a10258adf5312f5c830e30a4525cc4cc9b1fa87b0d36670ed659d490509436e3499a7ddbf8ff3b2729e26aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  petfinder_key: <%= ENV['PETFINDER_KEY'] %>
  petfinder_secret: <%= ENV['PETFINDER_SECRET'] %>
  RESCUE_GROUPS_API_KEY: <%= ENV['RESCUEGROUP_KEY'] %>
